services:
  server:
    container_name: server
    build: ./server
    ports: 
      - 5000:5000
    env_file:
      - ./server/.env.test
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres
    ports: 
      - 2345:5432
    env_file:
      - ./server/.env.test
