services:
  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    ports: 
      - 2345:5432
    env_file:
      - ./server/.env
    volumes:
      - db_volume:/var/lib/postgresql/data

  server:
    container_name: server
    build: ./server
    restart: on-failure
    ports: 
      - 5000:5000
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    
  client:
    container_name: client
    build: ./client
    env_file:
      - ./client/.env
    volumes:
      - client_volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./server/nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - client_volume:/var/www/html
    depends_on:
      - postgres
      - server
      - client
    
volumes:
  client_volume:
  db_volume: