name: Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create server .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          directory: server
          file_name: .env
          fail_on_empty: true

      - name: Create client .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_APP_BACKEND_URL: ${{secrets.VITE_APP_BACKEND_URL}}
          directory: client
          file_name: .env
          fail_on_empty: true

      - name: Stop active containers
        run: docker compose down

      - name: Delete client_volume if it exists
        run: if docker volume ls --quiet --filter name=password-generator-api_client_volume | grep -q .; then docker volume rm password-generator-api_client_volume; fi

      - name: Build new images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d
