name: Pull Request Actions
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          directory: server
          file_name: .env.test
          fail_on_empty: true

      - name: Run tests
        run: docker compose -f docker-compose.test.yml run server npm run test
