name: Pull Request Actions
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: 5000
          envkey_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/names?schema=public
          envkey_POSTGRES_PASSWORD: postgres
          directory: ./server
          file_name: .env.test
      - name: Run Tests
        run: docker compose -f docker-compose.test.yml run node npm run test
